### ISSUE TITLE
User/Register

### ISSUE THREAD

**Issue by ppmadalin** [ppmadalin/project-0#11]

**Comment by ppmadalin** [comment]
This function will allow an user to register as customer or as admin

**Comment by ppmadalin** [comment]
Need this function to link it up with my register page. :) 

Also I need to know how do you store the date information.

**Comment by ivoireNoire** [comment]
yes, still working on it because i have to test those methods. And after, i ll pulled them by request.
you will have and interface (low coupling) to call them from the register page.
the data will be store to a relational db throw a DAO

**Comment by ivoireNoire** [comment]
i just made a pull request.
PS: use those credentials on your side as i configured
UserDB => bancaDBUser
Password : 12345
If you plained anyway to use another one, do not forget to confirgure that on glassfish datasource

**Comment by ppmadalin** [comment]
If this functions has been implemented, please close this issue @ivoireNoire

**Comment by ivoireNoire** [comment]
this feature branch being merged, we should close this issue, isn't it?

**Comment by ppmadalin** [comment]
Yes! 😄  

We have to take care also of these issues. For example you have a few of them that are assigned to you and I am following these issue in order to know when you have finished a feature in order to start to implement that feature in the user interface.

**Comment by ivoireNoire** [comment]
morning :)
They all be ready soon. So i m closing this one

**Comment by ppmadalin** [comment]
Morning! Super! 
		
		

		Obțineți Outlook pentru iOS
	




On Fri, Aug 18, 2017 at 9:42 AM +0300, "Israel Dago" <notifications@github.com> wrote:












morning :)

They all be ready soon. So i m closing this one
