### ISSUE TITLE
Question: We need to discuss the application layout

### ISSUE THREAD

**Issue by ppmadalin** [ppmadalin/project-0#22]
We have to establish the application layout. 

#### My proposal:

- Header on the top of the page
- Menu with the actions on the left side of the page
- The content in the middle

**Comment by ppmadalin** [comment]
![proposal1](https://user-images.githubusercontent.com/5753617/28958771-5176b6f6-7900-11e7-8774-181413eda8ee.png)

**Comment by ivoireNoire** [comment]
Top, i see also the dashboard like that :)

**Comment by ppmadalin** [comment]
I am glad to hear that. We will keep this layout.
